name: Lint

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Prettier Check
        run: npm ci && npm run fmt

      - name: ESLint Check
        run: npm run lint
